Repository overture-stack/arranger, pull requests merged in 2018-02, with the labels that each got.

#126 🐛 nested / non-nested range sqon->es should work now
  modules/middleware/src/constants.js
  modules/middleware/src/filters.js
Labels: review

#128 🐛 aggregations middleware - more typos / other minor issues
  modules/middleware/src/aggregations.js
Labels: review

#129 replace fontawesome with react-icons
  modules/components/package.json
  modules/components/src/Admin/Dashboard.js
  modules/components/src/DataTable/TableToolbar/TableToolbar.js
Labels: review

#121 ✨ edit column type
  modules/components/src/Admin/ColumnsConfigTable.js
  modules/components/src/DataTable/EditColumns.js
Labels: review

#124 ✨ hook streaming back up and refactor server code
  modules/components/package.json
  modules/components/src/Admin/Dashboard.js
  modules/components/src/Aggs/AggsState.js
  modules/components/src/Arranger/Arranger.js
  modules/components/src/Arranger/GetProjects.js
  modules/components/src/Arranger/Table.js
  modules/components/src/DataTable/ColumnsState.js
  modules/components/src/DataTable/TableToolbar/saveTSV.js
  modules/components/src/DataTable/utils.js
  modules/components/src/Query.js
  modules/components/src/utils/api.js
  modules/components/src/utils/config.js
  modules/components/stories/table.js
  modules/mapping-utils/src/resolveHits.js
  modules/schema/src/Root.js
  modules/server/package.json
  modules/server/src/graphql.js
  modules/server/src/index.js
  modules/server/src/projects/index.js
  modules/server/src/projects/spinUp.js
  modules/server/src/projects/spinup.js
  modules/server/src/projects/teardown.js
  modules/server/src/socket.js
  modules/server/src/sockets/index.js
  modules/server/src/sockets/notifyOnUpdate.js
  modules/server/src/sockets/streamData.js
  modules/server/src/startProject.js
  modules/server/src/utils/config.js
  modules/server/src/utils/projects.js
Labels: review

#137 🐛 move div outside conditionally rendered section
  modules/components/public/themeStyles/beagle/beagle.css
  modules/components/src/Arranger/Aggregations.js
Labels: review

#136 ✨ allow calling server as CLI
  modules/server/README.md
  modules/server/index.js
  modules/server/package.json
Labels: review

#138 ✅ add test back to mapping-utils
  modules/mapping-utils/package.json
  modules/mapping-utils/src/utils.test.js
  modules/mapping-utils/test/getNestedFields.test.js
Labels: review

#135 ⬆️ update file-saver and normalize dep versions
  modules/components/package.json
  modules/components/src/DataTable/TableToolbar/saveTSV.js
  modules/faker/package.json
  modules/mapping-utils/package.json
  modules/middleware/package.json
  modules/schema/package.json
  modules/server/package.json
  package.json
Labels: review

#139 ⚡️ spinup single project via env
  modules/server/src/index.js
Labels: review

#131 🎨simplified some apis to help with other projects (capsid ;)
  modules/components/src/AdvancedFacetView/Facets/NumericAggregation.js
  modules/components/src/AdvancedFacetView/Facets/TermAggregation.js
  modules/components/src/Aggs/RangeAgg.js
  modules/components/src/Aggs/TermAgg.js
  modules/components/src/Arranger/Aggregations.js
  modules/components/src/Arranger/Table.js
  modules/components/src/DataTable/Table/Table.js
  modules/components/src/DataTable/TableToolbar/TableToolbar.js
  modules/components/src/SQONView/utils.js
  modules/components/stories/Aggs.js
  modules/server/package.json
Labels: review

#134 ✨ add dockerfile
  .dockerignore
  Dockerfile.server
Labels: review

#147 Githook
  modules/components/package.json
  modules/components/src/Admin/Dashboard.js
  modules/components/src/Arranger/DetectNewVersion.js
  modules/components/stories/Portal.js
  modules/components/yarn.lock
  modules/mapping-utils/src/mappingToDisplayTreeData.js
  modules/server/package.json
  modules/server/src/index.js
  modules/server/src/sockets/notifyOnUpdate.js
  modules/server/src/watchGit.js
Labels: review

#142 ✨ update netlify command so it's faster
  package.json
Labels: review

#153 🐛 match dotfield with __ for aggs
  modules/components/src/Aggs/AggsQuery.js
  modules/components/src/Arranger/Aggregations.js
Labels: review

#154 💄 update styles
  modules/components/public/themeStyles/beagle/beagle.css
Labels: review

#155 🐛 fix saveTSV row joining
  modules/components/src/DataTable/TableToolbar/saveTSV.js
Labels: review

#156 🐛forces value to be array for Aggregations type in advanced facet view
  modules/components/src/AdvancedFacetView/index.js
Labels: review

#164 ✅ test command from root
  .travis.yml
  modules/middleware/package.json
  modules/schema/package.json
  modules/server/package.json
  package.json
Labels: review

#133 ✨handles nesting in flattenMapping
  modules/mapping-utils/src/flattenMapping.js
  modules/mapping-utils/test/flattenMapping.test.js
Labels: MAPPING-UTILS, review

#171 🐛 defaultProps should be static
  modules/components/src/Arranger/DetectNewVersion.js
Labels: COMPONENTS

#163 ✨enable streamsaver
  modules/components/src/DataTable/TableToolbar/saveTSV.js
Labels: review

#158 🎨 separated text filter for external use
  modules/components/__mocks__/fileMock.js
  modules/components/__mocks__/styleMock.js
  modules/components/package.json
  modules/components/src/DataTable/TableToolbar/TableToolbar.js
  modules/components/src/SQONView/utils.js
  modules/components/src/TextFilter/TextFilter.js
  modules/components/src/TextFilter/__tests__/TextFilter.test.js
  modules/components/src/TextFilter/index.js
Labels: review

#165 ✨ updates the aggregations given the new sqon
  modules/components/package.json
  modules/components/src/AdvancedFacetView/LiveAdvancedFacetView.js
  modules/components/stories/AdvancedFacetView.js
Labels: COMPONENTS, review

#169 fixing export locations / test successful importing
  .dockerignore
  .gitignore
  integration-tests/import/.babelrc
  integration-tests/import/__mocks__/styleMock.js
  integration-tests/import/package.json
  integration-tests/import/test.js
  lerna.json
  modules/components/package.json
  modules/components/src/Admin/Dashboard.js
  modules/components/src/Admin/ProjectsTable.js
  modules/components/src/Admin/TypesTable.js
  modules/components/src/Arranger/index.js
  modules/components/src/index.js
  modules/components/stories/Dashboard.js
  modules/middleware/package.json
Labels: INTEGRATION-TESTS

#166 ✨ AFV facet filter box
  modules/components/public/themeStyles/beagle/beagle.css
  modules/components/src/AdvancedFacetView/SearchBox.js
  modules/components/src/AdvancedFacetView/index.js
  modules/components/src/AdvancedFacetView/utils.js
  modules/components/src/Input/Input.css
Labels: COMPONENTS, review

#176 ✨ Add download file endpoint
  modules/components/package.json
  modules/components/src/Arranger/Arranger.js
  modules/components/src/Arranger/Table.js
  modules/components/src/DataTable/DataTable.js
  modules/components/src/DataTable/TableToolbar/TableToolbar.js
  modules/components/src/DataTable/TableToolbar/saveTSV.js
  modules/components/src/DataTable/index.js
  modules/components/src/DataTable/utils.js
  modules/components/src/utils/api.js
  modules/components/src/utils/config.js
  modules/components/src/utils/download.js
  modules/components/stories/Portal.js
  modules/components/stories/table.js
  modules/faker/package.json
  modules/mapping-utils/src/utils/columnsToGraphql.js
  modules/middleware/package.json
  modules/server/package.json
  modules/server/src/download/index.js
  modules/server/src/sockets/streamData.js
  modules/server/src/startProject.js
  modules/server/src/utils/dataToTSV.js
  modules/server/src/utils/getAllData.js
Labels: review

#179 ✨ improvements to the search box
  modules/components/public/themeStyles/beagle/beagle.css
  modules/components/src/AdvancedFacetView/Facets/TermAggregation.js
  modules/components/src/AdvancedFacetView/Facets/index.js
  modules/components/src/AdvancedFacetView/LiveAdvancedFacetView.js
  modules/components/src/AdvancedFacetView/SearchBox.js
  modules/components/src/AdvancedFacetView/index.js
  modules/components/src/NestedTreeView/NestedTreeView.js
  modules/components/src/NestedTreeView/style.css
  modules/components/src/TextHighlight/index.js
  modules/components/stories/AdvancedFacetView.js
  modules/mapping-utils/src/flattenMapping.js
Labels: COMPONENTS, review

#187 🐛 aggregations middleware bug
  modules/middleware/package.json
  modules/middleware/src/aggregations.js
  modules/middleware/test/aggregations.test.js
Labels: review
