Repository overture-stack/arranger, pull requests merged in 2018-03, with the labels that each got.

#201 ✨ add withQuery
  modules/components/src/Query.js
  modules/components/src/index.js
Labels: review

#196 🐛Fix nested fields
  modules/mapping-utils/src/getNestedFields.js
  modules/mapping-utils/src/resolveHits.js
  modules/mapping-utils/test/getNestedFields.test.js
  modules/middleware/src/aggregations.js
Labels: MAPPING-UTILS, review

#197 ✨ remove unused first parameter
  modules/components/stories/table.js
  modules/mapping-utils/src/mappingToColumnsState.js
  modules/mapping-utils/src/utils/columnsToGraphql.js
Labels: MAPPING-UTILS, review

#193 ✨ object properties were being filtered out
  modules/mapping-utils/src/mappingToColumnsType.js
Labels: MAPPING-UTILS, review

#194 ✨ add mock option
  modules/server/src/download/index.js
  modules/server/src/startProject.js
  modules/server/src/utils/getAllData.js
  modules/server/src/utils/projects.js
Labels: review

#195 ✨ allow defining empty cell value
  modules/server/src/utils/dataToTSV.js
Labels: SERVER, review

#199 ✨ support reading directly from es mapping for quick fake data
  modules/faker/.babelrc
  modules/faker/package.json
  modules/faker/schemas/models.json
  modules/faker/src/export-data.js
  modules/faker/src/index.js
  modules/faker/src/schema-transformer.js
Labels: review

#198 🐛 make sure headers are written, even in empty tsv
  modules/server/src/utils/dataToTSV.js
  modules/server/src/utils/getAllData.js
Labels: SERVER, review

#210 Bug/afv text aggs
  modules/components/src/AdvancedFacetView/LiveAdvancedFacetView.js
Labels: COMPONENTS, review

#204 ✨ Adds ability to search values in the afv
  modules/components/package-lock.json
  modules/components/package.json
  modules/components/src/AdvancedFacetView/FacetView.js
  modules/components/src/AdvancedFacetView/FacetViewNode.js
  modules/components/src/AdvancedFacetView/Facets/TermAggregation.js
  modules/components/src/AdvancedFacetView/Facets/index.js
  modules/components/src/AdvancedFacetView/SearchBox.js
  modules/components/src/AdvancedFacetView/index.js
  modules/components/src/Aggs/TermAgg.js
  modules/components/src/State.js
Labels: COMPONENTS

#184 make use of "active" field on projects
  integration-tests/import/package-lock.json
  integration-tests/server/active.js
  integration-tests/server/connect.js
  integration-tests/server/index.test.js
  integration-tests/server/package-lock.json
  integration-tests/server/package.json
  integration-tests/server/power.js
  integration-tests/server/test.js
  modules/components/src/Admin/Dashboard.js
  modules/components/src/Admin/ProjectsTable.js
  modules/server/index.js
  modules/server/package-lock.json
  modules/server/package.json
  modules/server/src/index.js
  modules/server/src/projects/index.js
  modules/server/src/projects/updateProject.js
  modules/server/src/utils/ajax.js
  modules/server/src/utils/config.js
  package-lock.json
Labels: DASHBOARD, SERVER

#222 🐛 clone query result for jsonpath
  modules/server/src/utils/dataToTSV.js
Labels: review

#230 🐛 missing id reference
  modules/components/package-lock.json
  modules/components/package.json
  modules/server/src/utils/getAllData.js
  modules/server/src/utils/projects.js
Labels: review

#234 🐛use same get value function
  modules/server/src/utils/dataToTSV.js
  package-lock.json
Labels: review

#245 🐛 fix a few misc bugs causing incorrect global aggregation
  modules/middleware/src/aggregations.js
  modules/middleware/test/aggregations.test.js
Labels: review

#246 ✨ add boolean column type
  modules/components/src/DataTable/columnTypes.js
Labels: review

#248 Fixes extra border on last pagination button
  modules/components/public/themeStyles/beagle/beagle.css
Labels: review

#249 🐛 table bugs
  modules/components/public/themeStyles/beagle/beagle.css
  modules/components/src/DataTable/DataTable.js
  modules/components/src/DataTable/Table/CustomPagination.js
  modules/components/src/DataTable/Table/Table.js
  modules/components/src/DataTable/TableToolbar/TableToolbar.js
Labels: review

#247 🐛 fix null handling in get value
  modules/components/src/DataTable/utils.js
Labels: review

#250 ✨ allow configuring fields for filter
  modules/components/src/Arranger/Table.js
Labels: review

#258 🐛 use the right operator for jsonPath
  modules/components/stories/table.js
  modules/mapping-utils/src/mappingToColumnsState.js
  modules/server/src/utils/__tests__/dataToTSV.js
  modules/server/src/utils/dataToTSV.js
Labels: review

#264 🐛 pass sqon to download tsv button
  modules/components/src/DataTable/TableToolbar/TableToolbar.js
Labels: review

#266 ✨ if existing columns and new columns merge them
  modules/server/src/startProject.js
Labels: review

#279 implements ordering aggs and columns from admin dashboard
  modules/components/package-lock.json
  modules/components/package.json
  modules/components/src/Admin/Dashboard.js
  modules/components/src/Admin/Tabs/Aggregations/AggregationsTab.js
  modules/components/src/Admin/Tabs/Aggregations/TableTab.js
  modules/components/src/Admin/Tabs/DraggableListOrderer.js
  modules/components/src/Aggs/AggsState.js
  modules/components/src/Arranger/CurrentSQON.js
  modules/components/src/DataTable/ColumnsState.js
  modules/components/src/utils/api.js
  modules/components/stories/Dashboard.js
  modules/components/stories/Portal.js
  package-lock.json
Labels: DASHBOARD, review

#287 🐛 term agg - don't fall over if the bucket doesn't have a count
  modules/components/src/Aggs/TermAgg.js
Labels: COMPONENTS, review

#278 ✨ add custom column
  modules/components/package-lock.json
  modules/components/package.json
  modules/components/src/Admin/Tabs/Aggregations/TableTab.js
  modules/components/src/DataTable/AddCustomColumn.js
  modules/components/src/DataTable/ColumnsState.js
  modules/components/src/DataTable/EditColumns.js
  modules/components/src/DataTable/utils.js
  modules/mapping-utils/src/utils/columnsToGraphql.js
Labels: review

#289 Boolean aggs
  modules/components/src/Aggs/AggsWrapper.js
  modules/components/src/Aggs/BooleanAgg.css
  modules/components/src/Aggs/BooleanAgg.js
  modules/components/src/Aggs/RangeAgg.js
  modules/components/src/Aggs/TermAgg.js
  modules/components/src/Aggs/index.js
  modules/components/src/SQONView/utils.js
  modules/components/stories/Aggs.js
Labels: COMPONENTS, review

#282 ✨ middleware refactor - fixes aggregations
  modules/mapping-utils/src/buildAggregations.js
  modules/mapping-utils/src/buildQuery.js
  modules/mapping-utils/src/pruneAggregations.js
  modules/mapping-utils/src/resolveAggregations.js
  modules/mapping-utils/src/resolveHits.js
  modules/middleware/src/aggregations.js
  modules/middleware/src/buildAggregations.js
  modules/middleware/src/buildQuery/index.js
  modules/middleware/src/buildQuery/normalizeFilters.js
  modules/middleware/src/constants.js
  modules/middleware/src/filters.js
  modules/middleware/src/flattenAggregations.js
  modules/middleware/src/index.js
  modules/middleware/src/utils/esFilter.js
  modules/middleware/test/aggregations.test.js
  modules/middleware/test/buildAggregations.test.js
  modules/middleware/test/global_aggs.test.js
Labels: review

#284 ✨ middleware tests
  modules/middleware/test/buildAggregations.test.js
  modules/middleware/test/buildQuery/buildQuery.test.js
  modules/middleware/test/buildQuery/buildQueryNested.test.js
  modules/middleware/test/buildQuery/buildQuerySetId.test.js
  modules/middleware/test/buildQuery/buildQueryWildcard.test.js
  modules/middleware/test/flattenAggregations.test.js
Labels: review

#295 🐛 normalize / denormalize data in / out of range agg
  modules/components/src/Aggs/RangeAgg.js
Labels: COMPONENTS, review

#296 🐛 fix filter query
  modules/middleware/src/buildQuery/index.js
  modules/middleware/test/buildQuery/buildQueryFilter.test.js
Labels: review

#299 ✨ pass loading and error to children from query
  modules/components/src/Aggs/AggsPanel.js
  modules/components/src/Aggs/AggsQuery.js
  modules/components/src/Arranger/Aggregations.js
  modules/components/src/Query.js
Labels: review

#265 ✨ enable double nested colum configs
  modules/mapping-utils/src/mappingToColumnsType.js
Labels: review

#253 ✨lower chunk size
  modules/server/src/download/index.js
  modules/server/src/utils/getAllData.js
Labels: review

#298 🐛 global filters not working if query not wrapped in a group
  modules/middleware/src/buildAggregations.js
  modules/middleware/test/buildAggregations.test.js
Labels: review

#304 ✨ add prop to set page options showing
  modules/components/src/DataTable/DataTable.js
  modules/components/src/DataTable/Table/CustomPagination.js
  modules/components/src/DataTable/Table/Table.js
Labels: review

#290 ✨ support all regex
  modules/middleware/src/buildQuery/index.js
  modules/middleware/src/buildQuery/normalizeFilters.js
Labels: review

#301 Reimplements side bar in AFV
  modules/components/public/themeStyles/beagle/beagle.css
  modules/components/src/AdvancedFacetView/SearchBox.js
  modules/components/src/AdvancedFacetView/index.js
  modules/components/src/AdvancedFacetView/utils.js
  modules/components/src/NestedTreeView/NestedTreeView.js
  modules/components/src/NestedTreeView/ReactTreeView.js
  modules/components/src/NestedTreeView/style.css
  modules/components/src/TextHighlight/index.js
Labels: COMPONENTS, review

#269 ✨ add search_after param
  modules/mapping-utils/src/createConnectionResolvers.js
  modules/mapping-utils/src/createConnectionTypeDefs.js
  modules/mapping-utils/src/resolveHits.js
  modules/server/src/utils/dataToTSV.js
  modules/server/src/utils/getAllData.js
Labels: review
